import 'package:get/get_navigation/src/root/internacionalization.dart';

class MyLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'text_login':
              'Enter your mobile phone number',
          'enter_phone_number': 'Please enter your mobile number',
          'failed_phone_number': 'The entered mobile number is not correct',
          'failed_home_number': 'The entered home number is not correct',
          'required_phone_number': 'You must enter your mobile number',
          'required_home_number': 'You must enter your home number',
          'phone_number': 'PhoneNumber',
          'register_login': 'Sign Up and Log In',
          'login': 'Log In',
          'error_no_internet':
              'Internet connection error, please try again ...',
          'verification_code': 'Verification Code',
          'error_send_otp': 'Please enter the verification code sent via SMS',
          'resend': 'Resend',
          'verify_code': 'Verify Activation Code',
          'edit_number': 'Edit Number',
          'send_code_to_number':
              'The verification code has been sent via SMS to the number 09123456789',
          'alert_counter':
              'If you do not receive the code within 122 seconds, please try again',
          'complete_register': 'Complete your registration',
          'your_welcome': 'Welcome to Behesh, complete your registration',
          'try_again': 'Try Again',
          'farvardin': 'January',
          'ordibehesht': 'February',
          'khordad': 'March',
          'tir': 'April',
          'mordad': 'May',
          'shahrivar': 'June',
          'mehr': 'July',
          'aban': 'August',
          'azar': 'September',
          'dey': 'October',
          'bahman': 'November',
          'esfand': 'December',
          'enter_first_name': 'Enter your first name',
          'first_name': 'First Name',
          'enter_surname_name': 'Enter your surname',
          'surname_name': 'Surname',
          'birthday': 'Birthday',
          'required_birthday': 'Specify your birthdate',
          'select_birthdate': 'Select Birthdate',
          'select_date': 'Select Date',
          'day':'Day',
          'month':"Month",
          'year':"Year",
          "complete_profile": "Complete Profile",
          'save_change': 'Save Changes',
          'save_and_return': 'Save and return',
          'exit':'Exit',
          'close':'Close',
          'confirm_exit_account':
          'Are you sure about logging out of your account?',
        },
        'fa_IR': {
          'text_login': 'شماره تلفن همراه خود را وارد کنید',
          'enter_phone_number': 'شماره موبایل خود را وارد کنید',
          'failed_phone_number': 'شماره موبایل وارد شده صحیح نمی باشد',
          'failed_home_number': 'شماره تلفن وارد شده صحیح نمی باشد',
          'required_phone_number': 'باید شماره موبایل خود را وارد نمایید',
          'required_home_number': 'باید شماره تلفن خود را وارد نمایید',
          'phone_number': 'شماره موبایل',
          'register_login': 'ثبت نام و ورود',
          'login': 'ورود',
          'error_no_internet': 'خطا در اتصال اینترنت, دوباره سعی کنید ...',
          'verification_code': 'کد تایید',
          'error_send_otp': 'کد تایید پیامک شده را وارد کنید',
          'resend': 'ارسال مجدد',
          'verify_code': 'تایید',
          'edit_number': 'ویرایش شماره',
          'send_code_to_number': 'کد تایید برای شماره 09123456789 پیامک شد',
          'alert_counter':
              'لطفا 1000 ثانیه صبر کنید، ',
          'complete_register': 'ثبت نام خود را تکمیل کنید',
          'your_welcome': 'به بهشت خوش اومدی، ثبت نامتو تکمیل کن',
          'try_again': 'تلاش دوباره',
          'farvardin': 'فروردین',
          'ordibehesht': 'اردیبهشت',
          'khordad': 'خرداد',
          'tir': 'تیر',
          'mordad': 'مرداد',
          'shahrivar': 'شهریور',
          'mehr': 'مهر',
          'aban': 'آبان',
          'azar': 'آذر',
          'dey': 'دی',
          'bahman': 'بهمن',
          'esfand': 'اسفند',
          'first_name': 'نام',
          'enter_first_name': 'نام خود را وارد کنید',
          'surname_name': 'نام خانوادگی',
          'enter_surname_name': 'نام خانوادگی خود را وارد کنید',
          'birthday': 'تاریخ تولد',
          'required_birthday': 'تاریخ تولد خود را مشخص کنید',
          'select_birthdate': 'انتخاب تاریخ تولد',
          'select_date': 'انتخاب تاریخ',
          'day':'روز',
          'month':"ماه",
          'year':"سال",
          "complete_profile": "تکمیل پروفایل",
          'save_change': 'ذخیره تغییرات',
          'save_and_return': 'ذخیره و بازگشت',
          'exit':'خروج',
          'close':'بستن',
          'confirm_exit_account': 'آیا از خروج حساب کاربری مطمئن هستید؟',

        },
      };
}
